// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const suggest: Partial<Config> = {
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.ui-input-suggest': {
          '&__item': {
            height: '3rem',
            gap: "var(--radius-8)",
            padding: "var(--radius-8) var(--radius-12)",
            borderRadius: "var(--radius-12)",
            color: "rgb(var(--color-neutral-600) / 1)",

            '&[aria-selected="true"]': {
              cursor: 'not-allowed',
              '.ui-input-suggest__leading-icon, .ui-input-suggest__label': {
                opacity: '0.45',
              },
            },

            '&:hover, &[data-active="true"]': {
              backgroundColor: "rgb(var(--color-neutral-100) / 1)",
            }
          },
        },
      })
    })
  ],
}

export default suggest
