// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex flex-col max-h-[20rem] min-h-[6.75rem] overflow-scroll absolute top-full left-0 right-0 mt-8 bg-white rounded-12 gap-[var(--spacing-4)] p-[var(--spacing-4)]",
    "slots": {
        "item": "flex shrink-0 grow-0 items-center h-[3rem] gap-[var(--spacing-8)] py-[var(--spacing-8)] px-[var(--spacing-12)] rounded-12 hover:bg-neutral-100 aria-selected:bg-neutral-100 text-neutral-600 text-body font-medium text-nowrap"
    }
} as const

export default button