// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex flex-col max-h-[20rem] min-h-[6.75rem] overflow-scroll absolute top-full left-0 right-0 mt-8 bg-[var(--component-input-list-bg)] rounded-[var(--radius-list)] gap-[var(--spacing-4)] p-[var(--spacing-4)]",
    "slots": {
        "item": "flex shrink-0 grow-0 items-center h-[3rem] gap-[var(--spacing-8)] py-[var(--spacing-8)] px-[var(--spacing-12)] rounded-[var(--radius-list)] hover:bg-[var(--component-input-list-hover)] aria-selected:bg-[var(--component-input-list-hover)] text-[var(--component-input-list-suggest-text-default)] text-body font-medium text-nowrap"
    }
} as const

export default button