// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex flex-col max-h-[20rem] overflow-y-auto overflow-x-hidden",
    "slots": {
        "floating": "absolute top-full left-0 right-0 mt-8",
        "panel": "bg-white rounded-12 gap-4 p-4",
        "embedded": "gap-4 p-4",
        "icon": "text-neutral-400",
        "empty": "text-neutral-600 text-body font-medium"
    }
} as const

export default button