// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "relative flex flex-col items-start overflow-hidden rounded-16",
    "variant": {
        "default": "bg-bg-surface",
        "outlined": "border border-neutral-200/80 bg-bg-surface",
        "alt": "border border-neutral-200/80 bg-bg-surface-alt",
        "gradient": "bg-gradient-card"
    },
    "slots": {
        "content": "w-full"
    }
} as const

export default button