// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "relative flex flex-col items-start overflow-hidden rounded-16",
    "variant": {
        "default": "bg-page-surface",
        "outlined": "border border-neutral-200/80 bg-page-surface",
        "alt": "border border-neutral-200/80 bg-page-surface-alt",
        "gradient": "bg-gradient-card"
    }
} as const

export default button