// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex flex-col max-h-[20rem] overflow-hidden absolute top-full left-0 right-0 mt-8 bg-neutral-300 rounded-16 gap-4 p-4",
    "slots": {
        "item": "flex shrink-0 grow-0 items-center cursor-pointer h-[3rem] gap-8 py-8 px-12 rounded-16 hover:bg-neutral-200/40 aria-selected:bg-neutral-200/40 text-white text-body font-medium text-nowrap",
        "icon": "text-neutral-100"
    }
} as const

export default button