// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex flex-col max-h-[20rem] min-h-[6.75rem] overflow-scroll absolute top-full left-0 right-0 mt-8 bg-neutral-300 rounded-16 gap-1 p-1",
    "slots": {
        "item": "flex shrink-0 grow-0 items-center h-[3rem] gap-2 py-2 px-3 rounded-16 hover:bg-neutral-200/40 aria-selected:bg-neutral-200/40 text-white text-body font-medium text-nowrap"
    }
} as const

export default button