// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "inline-flex items-center justify-center gap-1 overflow-hidden shrink-0 whitespace-nowrap",
    "size": {
        "default": {
            "container": "h-5 px-2 rounded-full",
            "dot": "h-2 w-2 rounded-full shrink-0",
            "text": "text-caption font-medium tabular-nums"
        }
    },
    "variant": {
        "filled": {
            "container": "bg-[rgb(var(--color-neutral-100))]",
            "text": "text-[rgb(var(--color-neutral-800))]"
        },
        "ghost": {
            "container": "",
            "text": "text-white"
        }
    },
    "state": {
        "start": "bg-[rgb(var(--color-primary-300))]",
        "finish": "bg-[rgb(var(--color-success-100))]",
        "threshold": "bg-[rgb(var(--color-error-100))]",
        "over": "bg-[rgb(var(--color-error-100))]"
    },
    "slots": {
        "text": "text-caption font-medium tabular-nums"
    }
} as const

export default button