// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type {Config} from "tailwindcss";
import plugin from "tailwindcss/plugin";

const button: Partial<Config> = {
    plugins: [
        plugin(({ addComponents }) => {
            addComponents({
                '.ui-switcher': {
                    '&__track': {
                        backgroundColor: "rgb(var(--color-neutral-100) / 1)",
                    },
                    '&__thumb': {
                        backgroundColor: "rgb(var(--color-neutral-100) / 1)",
                        left: '0%'
                    },
                    '&.selected .ui-switcher__track': {
                        backgroundColor: "rgb(var(--color-primary-300) / 1)",
                    },
                    '&.selected .ui-switcher__thumb': {
                        backgroundColor: "rgb(var(--color-primary-300) / 1)",
                        right: '0%',
                        left: 'auto',
                    },
                    '&[data-invalid="true"] .ui-switcher__track, &[data-invalid="true"] .ui-switcher__thumb': {
                        backgroundColor: "var(--fg-status-error)",
                    },
                    '&[data-disabled="true"] .ui-switcher__label': {
                        opacity: '0.45',
                    },
                },
            })
        }),
    ],
}

export default button
