// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "inline-flex items-center justify-center overflow-hidden shrink-0 upper-case",
    "size": {
        "default": {
            "container": "h-24 rounded-full p-8",
            "label": "text-caption font-bold uppercase whitespace-nowrap"
        }
    },
    "variant": {
        "status-error": "bg-error-100 text-neutral-500",
        "status-warning": "bg-warning-100 text-neutral-500",
        "status-success": "bg-success-100 text-neutral-500",
        "navigation-default": "bg-warning-100 text-neutral-500",
        "navigation-new": "bg-error-100 text-neutral-500",
        "neutral": "bg-neutral-300/80 text-white",
        "personal": "bg-gradient-personal text-neutral-500"
    },
    "slots": {
        "label": "text-caption font-bold uppercase whitespace-nowrap"
    }
} as const

export default button