// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-progress-bar flex flex-col text-caption gap-2",
    "full": "h-2 w-full bg-neutral-300 rounded-full overflow-hidden",
    "progress": "bg-gradient-personal h-2 rounded-full"
} as const

export default button