// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const carousel: Partial<Config> = {
  plugins: [
    plugin(({ addBase, addComponents }) => {
      addBase({
        '@property --ui-carousel-mask-left-opacity': {
          syntax: '"<number>"',
          inherits: 'true',
          initialValue: '1',
        },
        '@property --ui-carousel-mask-right-opacity': {
          syntax: '"<number>"',
          inherits: 'true',
          initialValue: '1',
        },
      })

      addComponents({
        '.ui-carousel': {
          '--ui-carousel-mask-fade-size': '1rem',
          position: 'relative',
          width: '100%',

          '@screen md': {
            '--ui-carousel-mask-fade-size': '4rem',
          },

          '&:hover .ui-carousel-navigation__button': {
            opacity: '1',
            transform: 'scale(1)',
          },

          '&__viewport': {
            '--ui-carousel-mask-left-opacity': '1',
            '--ui-carousel-mask-right-opacity': '1',
            display: 'flex',
            minHeight: '2.5rem',
            alignItems: 'center',
            gap: "var(--radius-12)",
            paddingInline: "var(--radius-24)",
            overflowX: 'auto',
            overflowY: 'hidden',
            scrollBehavior: 'smooth',
            scrollSnapType: 'x mandatory',
            scrollbarWidth: 'none',
            maskImage: "linear-gradient(to right, rgba(0, 0, 0, var(--ui-carousel-mask-left-opacity)) 0%, #000 var(--ui-carousel-mask-fade-size), #000 calc(100% - var(--ui-carousel-mask-fade-size)), rgba(0, 0, 0, var(--ui-carousel-mask-right-opacity)) 100%)",
            maskRepeat: 'no-repeat',
            transition: '--ui-carousel-mask-left-opacity 0.3s ease-out, --ui-carousel-mask-right-opacity 0.3s ease-out',

            '&::-webkit-scrollbar': {
              display: 'none',
            },

            '& > *': {
              flex: '0 0 auto',
              scrollSnapAlign: 'start',
            },

            '@screen md': {
              gap: "var(--spacing-20)",
            },

            '@media (prefers-reduced-motion: reduce)': {
              scrollBehavior: 'auto',
              transition: 'none',
            },
          },

          '&--start &__viewport, &--middle &__viewport': {
            '--ui-carousel-mask-right-opacity': '0',
          },

          '&--scrolling &__viewport, &--end:not(.ui-carousel--center-active-slide) &__viewport, &--middle.ui-carousel--center-active-slide &__viewport': {
            '--ui-carousel-mask-left-opacity': '0',
          },

          '&--center-active-slide &__viewport > *': {
            scrollSnapAlign: 'center',
          },

          '&:not(.ui-carousel--center-active-slide) &__viewport > *': {
            scrollMarginInlineStart: "var(--radius-24)",
          },

          '&--middle:not(.ui-carousel--scrolling):not(.ui-carousel--center-active-slide) &__viewport': {
            clipPath: "inset(0 0 0 var(--radius-24))",
          },
        },

        '.ui-carousel-navigation': {
          position: 'absolute',
          inset: '0',
          zIndex: '2',
          display: 'none',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: "var(--radius-8) var(--radius-16)",
          pointerEvents: 'none',

          '@screen md': {
            display: 'flex',
          },

          '&__button': {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '2rem',
            height: '100%',
            minHeight: '1.5rem',
            maxHeight: '5rem',
            padding: '0',
            border: '0',
            borderRadius: "var(--radius-8)",
            color: "var(--fg-page-secondary)",
            background: "var(--bg-page-surface)",
            boxShadow: "0 4px 8px 0 var(--color-neutral-800-10)",
            WebkitBackdropFilter: "none",
            backdropFilter: "none",
            cursor: 'pointer',
            opacity: '0',
            pointerEvents: 'auto',
            transform: 'scale(0.7)',
            transition: 'opacity 0.3s ease-out, transform 0.3s ease-out',

            '&:focus-visible': {
              outline: '2px solid currentColor',
              outlineOffset: '2px',
              opacity: '1',
              transform: 'scale(1)',
            },

            '@media (prefers-reduced-motion: reduce)': {
              transition: 'none',
            },
          },

          '&__button--next': {
            marginLeft: 'auto',
          },
        },
      })
    }),
  ],
}

export default carousel
