// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-input group flex flex-col relative gap-4 data-[disabled=true]:opacity-45",
    "size": {
        "default": {
            "field": "rounded-16 h-14 py-8 px-12 h-auto items-start"
        }
    },
    "slots": {
        "field": "flex items-center w-full overflow-hidden border-solid [border:0.125rem_solid_var(--color-transparent)] gap-8 bg-neutral-200/40 hover:[&:not(:focus-within):not([data-invalid=true]):not([data-disabled=true])]:border-primary-50 focus-within:border-primary-300 data-[invalid=true]:[&:not(:focus-within)]:border-error-100 items-start",
        "content": "relative flex min-w-0 flex-1 flex-col",
        "label": "text-caption font-medium left-0 origin-left transition-all duration-200 ease-out cursor-text w-full text-body font-medium duration-150 text-neutral-100 group-data-[invalid=true]:text-error-100 group-focus-within:!text-primary-300 min-w-0 truncate",
        "value": "text-body font-normal placeholder:font-normal w-full min-w-0 border-0 bg-transparent p-0 outline-none placeholder:opacity-100 disabled:cursor-not-allowed h-[5.25rem] resize-none overflow-scroll leading-[inherit] text-white placeholder:text-neutral-100",
        "messageRow": "px-16 text-neutral-100 group-data-[invalid=true]:text-error-100 group-focus-within:!text-neutral-100 text-caption flex w-full items-start gap-8",
        "message": "min-w-0 flex-1",
        "errorMessage": "flex gap-4 group-data-[invalid=true]:text-error-100 group-focus-within:text-neutral-100",
        "counter": "shrink-0 text-right whitespace-nowrap"
    }
} as const

export default button