// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-input",
    "size": {
        "default": {
            "field": "h-auto items-start"
        }
    },
    "slots": {
        "field": "ui-input__field items-start",
        "content": "relative flex min-w-0 flex-1 flex-col",
        "label": "ui-input__label text-caption font-medium min-w-0 truncate",
        "value": "text-body font-normal placeholder:font-normal w-full min-w-0 border-0 bg-transparent p-0 outline-none placeholder:opacity-100 disabled:cursor-not-allowed h-[5.25rem] resize-none overflow-scroll leading-[inherit] text-neutral-600 placeholder:text-neutral-300",
        "messageRow": "ui-input__message flex w-full items-start gap-8",
        "message": "min-w-0 flex-1",
        "errorMessage": "ui-input__error-message",
        "counter": "shrink-0 text-right whitespace-nowrap"
    }
} as const

export default button