import type { Meta, StoryObj } from '@storybook/vue3-vite'
import { reactive, ref } from 'vue'
import UITextArea from '../../components/form/basicControls/textArea/UITextArea.vue'

type TextAreaStoryArgs = {
  modelValue: string
  name: string
  label: string
  placeholder: string
  disabled: boolean
  invalid: boolean
  errorMessages: string
  message: string
  maxlength?: number
  rows: number
  resize: 'none' | 'vertical' | 'horizontal' | 'both'
}

const meta = {
  title: 'Components/Form/TextArea',
  component: UITextArea,
  tags: ['autodocs'],
  args: {
    modelValue: '',
    name: 'storybook-textarea',
    label: 'Comment',
    placeholder: 'Tell us more',
    disabled: false,
    invalid: false,
    errorMessages: '',
    message: 'Message',
    maxlength: 100,
    rows: 3,
    resize: 'none',
  },
  argTypes: {
    modelValue: { control: 'text' },
    name: { control: 'text' },
    label: { control: 'text' },
    placeholder: { control: 'text' },
    disabled: { control: 'boolean' },
    invalid: { control: 'boolean' },
    errorMessages: { control: 'text' },
    message: { control: 'text' },
    maxlength: { control: 'number' },
    rows: { control: 'number' },
    resize: {
      control: 'select',
      options: ['none', 'vertical', 'horizontal', 'both'],
    },
  },
} satisfies Meta<TextAreaStoryArgs>

export default meta
type Story = StoryObj<typeof meta>

export const Playground: Story = {
  parameters: {
    controls: { disable: true },
    layout: 'fullscreen',
  },
  render: (args) => ({
    components: { UITextArea },
    setup() {
      const value = ref(args.modelValue)

      return {
        args,
        value,
      }
    },
    template: `
      <div class="p-6 bg-bg-deep">
        <UITextArea
          v-bind="args"
          v-model="value"
          class="max-w-[24rem]"
        />
      </div>
    `,
  }),
}

export const PropsMatrix: Story = {
  parameters: {
    controls: { disable: true },
    layout: 'fullscreen',
  },
  render: () => ({
    components: { UITextArea },
    setup() {
      const sections = reactive([
        {
          title: 'Base states',
          items: [
            {
              title: 'Empty',
              value: '',
              props: {
                name: 'empty',
                label: 'Comment',
                placeholder: 'Add your comment',
                message: 'Message',
                maxlength: 100,
              },
            },
            {
              title: 'Filled',
              value: 'The onboarding flow is clear, but the final confirmation step still feels abrupt.',
              props: {
                name: 'filled',
                label: 'Feedback',
                placeholder: 'Share your thoughts',
                message: 'Message',
                maxlength: 140,
              },
            },
            {
              title: 'Disabled',
              value: 'Autogenerated text is locked for editing.',
              props: {
                name: 'disabled',
                label: 'Generated summary',
                placeholder: 'This field is disabled',
                disabled: true,
                message: 'Message',
                maxlength: 100,
              },
            },
          ],
        },
        {
          title: 'Validation and sizing',
          items: [
            {
              title: 'Invalid',
              value: 'Too short',
              props: {
                name: 'invalid',
                label: 'Issue description',
                placeholder: 'Describe the issue',
                invalid: true,
                errorMessages: 'Please provide more details.',
                maxlength: 120,
              },
            },
            {
              title: 'Counter only',
              value: 'A compact note with character count enabled.',
              props: {
                name: 'counter',
                label: 'Internal note',
                placeholder: 'Write a note',
                message: '',
                maxlength: 60,
              },
            },
            {
              title: 'Resizable',
              value: '',
              props: {
                name: 'resizable',
                label: 'Detailed description',
                placeholder: 'You can drag the corner to resize',
                rows: 5,
                resize: 'vertical',
                message: 'Message',
                maxlength: 240,
              },
            },
          ],
        },
      ])

      return {
        sections,
      }
    },
    template: `
      <div class="space-y-6 bg-bg-deep p-6">
        <section
          v-for="section in sections"
          :key="section.title"
          class="rounded-3xl border border-white/10 bg-white/5 p-5"
        >
          <div class="mb-4 text-sm font-medium uppercase tracking-[0.08em] text-fg-secondary">
            {{ section.title }}
          </div>

          <div class="grid gap-4 md:grid-cols-3">
            <div
              v-for="item in section.items"
              :key="item.title"
              class="rounded-2xl border border-white/10 bg-black/10 p-4"
            >
              <div class="mb-3 text-caption text-fg-secondary">
                {{ item.title }}
              </div>

              <UITextArea
                v-bind="item.props"
                :model-value="item.value"
                @update:model-value="item.value = $event"
              />
            </div>
          </div>
        </section>
      </div>
    `,
  }),
}
