// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex items-center overflow-x-auto min-h-px min-w-px gap-4",
    "item": {
        "base": "flex shrink-0 items-center justify-center transition-colors rounded-16 px-16 py-8 gap-8",
        "default": "text-neutral-100",
        "hover": "hover:bg-neutral-200/80 hover:text-white",
        "selected": "bg-neutral-50/10 text-primary-400",
        "disabled": "pointer-events-none opacity-45"
    },
    "slots": {
        "label": "text-body-sm font-bold uppercase whitespace-nowrap text-center",
        "accent": "size-8 shrink-0 rounded-full bg-fg-status-error"
    }
} as const

export default button