// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-faq-item flex flex-col overflow-hidden border transition-colors rounded-12 text-fg-primary px-16 py-12 py-8",
    "slots": {
        "iconOpened": "rotate-180"
    },
    "states": {
        "opened": "border-primary-100 bg-primary-50/80",
        "default": "border-neutral-800/10 bg-neutral-100"
    }
} as const

export default button