// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-progress-bar flex flex-col text-caption gap-4",
    "full": "h-8 w-full bg-neutral-800/10 rounded-full overflow-hidden",
    "progress": "bg-gradient-personal h-8 rounded-full"
} as const

export default button