// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "relative",
    "slots": {
        "trigger": "inline-flex",
        "content": "text-caption font-medium min-w-52 p-8 rounded-8 bg-secondary-300 text-fg-primary"
    }
} as const

export default button