// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "relative",
    "slots": {
        "trigger": "inline-flex",
        "content": "p-2 text-caption font-medium min-w-52 rounded-8 bg-secondary-300 text-fg-primary",
        "arrow": "absolute rotate-45 w-2 h-2 bg-secondary-300"
    }
} as const

export default button