// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "fixed z-9999 w-84 max-w-full-mob top-16 right-16",
    "slots": {
        "list": "flex flex-col gap-12",
        "item": "flex p-16 gap-8"
    },
    "transitionGroup": {
        "enterActiveClass": "transition-opacity duration-500",
        "enterFromClass": "opacity-0",
        "leaveActiveClass": "transition-opacity duration-500",
        "leaveToClass": "opacity-0"
    }
} as const

export default button