// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "fixed z-9999 w-84 max-w-full-mob top-4 right-4",
    "slots": {
        "list": "flex flex-col gap-3",
        "item": "flex p-4 gap-2"
    },
    "transitionGroup": {
        "enterActiveClass": "transition-opacity duration-500",
        "enterFromClass": "opacity-0",
        "leaveActiveClass": "transition-opacity duration-500",
        "leaveToClass": "opacity-0"
    }
} as const

export default button