// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type {Config} from "tailwindcss";
import plugin from "tailwindcss/plugin";

const button: Partial<Config> = {
    plugins: [
        plugin(({ addComponents }) => {
            addComponents({
                '.ui-button': {
                    '&.primary': {
                        '.ui-button--primary': {
                            background: "linear-gradient(to right, rgb(var(--color-primary-400) / 1) 0%, rgb(var(--color-primary-100) / 1) 100%)",
                            color: "rgb(var(--color-neutral-500) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--primary': {
                            background: "rgb(var(--color-primary-300) / 1)",
                            color: "rgb(var(--color-neutral-500) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--primary, &[aria-busy="true"] .ui-button--primary': {
                            background: "rgb(var(--color-primary-200) / 1)",
                            color: "rgb(var(--color-neutral-500) / 1)",
                        },
                    },

                    '&.destructive': {
                        '.ui-button--destructive': {
                            background: "rgb(var(--color-error-100) / 1)",
                            color: "var(--color-black)",
                        },

                        '&:not(:disabled):hover .ui-button--destructive': {
                            background: "rgb(var(--color-error-100) / 0.8)",
                            color: "var(--color-black)",
                        },

                        '&:not(:disabled):active .ui-button--destructive, &[aria-busy="true"] .ui-button--destructive': {
                            background: "rgb(var(--color-error-100) / 1)",
                            color: "var(--color-black)",
                        },
                    },

                    '&.secondary': {
                        '.ui-button--secondary': {
                            borderWidth: '2px',
                            borderColor: "rgb(var(--color-primary-300) / 1)",
                            background: "rgb(var(--color-neutral-400) / 0.4)",
                            color: "rgb(var(--color-white))",
                        },

                        '&:not(:disabled):hover .ui-button--secondary': {
                            borderColor: "rgb(var(--color-primary-300) / 1)",
                            background: "rgb(var(--color-neutral-200) / 0.4)",
                            color: "rgb(var(--color-white))",
                        },

                        '&:not(:disabled):active .ui-button--secondary, &[aria-busy="true"] .ui-button--secondary': {
                            borderColor: "rgb(var(--color-primary-100) / 1)",
                            background: "rgb(var(--color-neutral-400) / 0.4)",
                            color: "rgb(var(--color-neutral-50) / 1)",
                        },
                    },

                    '&.tertiary': {
                        '.ui-button--tertiary': {
                            background: "rgb(var(--color-neutral-100) / 0.1)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--tertiary': {
                            background: "rgb(var(--color-neutral-200) / 0.4)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--tertiary, &[aria-busy="true"] .ui-button--tertiary': {
                            background: "rgb(var(--color-neutral-50) / 0.1)",
                            color: "rgb(var(--color-primary-50) / 1)",
                        },
                    },

                    '&.ghost': {
                        '.ui-button--ghost': {
                            background: "var(--color-transparent)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--ghost': {
                            background: "rgb(var(--color-neutral-100) / 0.1)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--ghost, &[aria-busy="true"] .ui-button--ghost': {
                            background: "rgb(var(--color-neutral-50) / 0.1)",
                            color: "rgb(var(--color-primary-50) / 1)",
                        },
                    },

                    '&:disabled:not([aria-busy="true"])': {
                        '&.primary, &.destructive': {
                            opacity: '0.25'
                        },
                        '&.secondary, &.tertiary, &.ghost': {
                            opacity: '0.45'
                        }
                    },
                    '&[aria-busy="true"]:not(.slab)': {
                        '.ui-button__main-icon': {
                            opacity: '0'
                        }
                    },

                    '.ui-button__loading-overlay': {
                        '@apply absolute inset-0': {},
                        background: "rgb(var(--color-neutral-500) / 0.8)",
                    },
                    '.ui-button__loading-icon': {
                        '@apply size-32': {}
                    },

                    '&.slab': {
                        '&.tertiary-alt ': {
                            '.ui-button--tertiary': {
                                background: "rgb(var(--color-neutral-100) / 0.1)",
                                border: "2px solid rgb(var(--color-neutral-50) / 0.1)",
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    background: "rgb(var(--color-neutral-50) / 0.1)",
                                    color: "rgb(var(--color-white))",
                                },
                                '&:active': {
                                    background: "rgb(var(--color-neutral-50) / 0.1)",
                                    color: "rgb(var(--color-white))",
                                },
                                '&:hover, &:active, &:disabled': {
                                    borderColor: 'transparent',
                                }
                            }
                        }
                    },
                    '&.icon': {
                        '&.tertiary-alt': {
                            '.ui-button--tertiary': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-white))",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-white))",
                                },
                            }
                        },
                        '&.ghost-alt': {
                            '.ui-button--ghost': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "var(--component-button-ghost-hover-alt-fg)",
                                },
                                '&:active': {
                                    color: "var(--component-button-ghost-pressed-alt-fg)",
                                },
                            }
                        }
                    },
                    '&.action': {
                        '&.tertiary-alt': {
                            '.ui-button--tertiary': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-white))",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-white))",
                                },
                            }
                        }
                    }
                },
            })
        }),
    ],
}

export default button
