// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type {Config} from "tailwindcss";
import plugin from "tailwindcss/plugin";

const button: Partial<Config> = {
    plugins: [
        plugin(({ addComponents }) => {
            addComponents({
                '.ui-button': {
                    '&.slab': {
                        '&.tertiary-alt ': {
                            '.ui-button__content': {
                                backgroundColor: "rgb(var(--color-neutral-100) / 0.1)",
                                border: "2px solid rgb(var(--color-neutral-50) / 0.1)",
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    backgroundColor: "rgb(var(--color-neutral-50) / 0.1)",
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                                '&:active': {
                                    backgroundColor: "rgb(var(--color-neutral-100) / 0.4)",
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                                '&:hover, &:active, &:disabled': {
                                    borderColor: 'transparent',
                                }
                            }
                        }
                    },
                    '&.icon': {
                        '&.tertiary-alt': {
                            '.ui-button__content': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                            }
                        },
                        '&.ghost-alt': {
                            '.ui-button__content': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                            }
                        }
                    },
                    '&.action': {
                        '&.tertiary-alt': {
                            '.ui-button__main-icon': {
                                color: "rgb(var(--color-neutral-50) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-50) / 1)",
                                },
                            }
                        }
                    }
                },
            })
        }),
    ],
}

export default button
