// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex cursor-pointer",
    "type": {
        "standard": {
            "base": "flex-row items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "h-32 gap-4 rounded-8 px-12 py-4",
                    "icon": "!w-16 !h-16",
                    "label": "text-button-sm truncate"
                },
                "md": {
                    "container": "h-40 gap-4 rounded-8 px-12 py-8",
                    "icon": "",
                    "label": "text-button-md truncate"
                },
                "lg": {
                    "container": "h-[3rem] gap-8 rounded-8 px-16 py-12",
                    "icon": "",
                    "label": "text-button-lg truncate"
                }
            }
        },
        "icon": {
            "base": "aspect-square p-0 flex items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "h-32 rounded-full",
                    "icon": "!w-16 !h-16"
                },
                "md": {
                    "container": "h-40 rounded-full",
                    "icon": "w-24"
                },
                "lg": {
                    "container": "h-[3rem] rounded-full",
                    "icon": "w-24"
                }
            }
        },
        "caption": {
            "base": "flex-col text-center justify-center items-center",
            "sizes": {
                "sm": {
                    "container": "h-[3rem] gap-2 rounded-8 px-16 py-4",
                    "label": "text-button-sm truncate",
                    "caption": "text-button-caption truncate opacity-85"
                },
                "md": {
                    "container": "h-[3.5rem] gap-4 rounded-8 px-24 py-4",
                    "label": "text-button-md truncate",
                    "caption": "text-button-caption truncate opacity-85"
                },
                "lg": {
                    "container": "h-[4rem] gap-4 rounded-8 px-24 py-4",
                    "label": "text-button-lg truncate",
                    "caption": "text-button-caption truncate opacity-85"
                }
            }
        },
        "slab": {
            "base": "flex-col items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "h-[3.5rem] gap-4 rounded-16 px-16 py-4",
                    "icon": "w-6",
                    "label": "text-button-caption truncate"
                }
            }
        },
        "action": {
            "base": "flex-col items-center justify-center text-center gap-[0.375rem] gap-[0.375rem]",
            "sizes": {
                "sm": {
                    "container": "flex justify-center items-center w-[3rem] h-[3rem] rounded-full",
                    "icon": "w-6",
                    "label": "text-button-caption text-white truncate"
                }
            }
        }
    },
    "variant": {
        "primary": {
            "base": "bg-primary-300 text-neutral-500 group-aria-busy:opacity-0",
            "hover": "group-hover:bg-primary-200 group-hover:text-neutral-500",
            "pressed": "group-active:bg-primary-100 group-active:text-neutral-500",
            "loading": "group-aria-busy:bg-primary-100 group-aria-busy:text-neutral-500",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        },
        "secondary": {
            "base": "border-2 border-primary-300 bg-primary-300/10 text-white group-aria-busy:opacity-0",
            "hover": "group-hover:border-primary-200 group-hover:bg-primary-200/10 group-hover:text-white",
            "pressed": "group-active:border-primary-100 group-active:bg-primary-100/10 group-active:text-white",
            "loading": "border-2 group-aria-busy:border-primary-100 group-aria-busy:bg-primary-100/10 group-aria-busy:text-white",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "tertiary": {
            "base": "border-transparent bg-neutral-200/40 text-primary-300 group-aria-busy:opacity-0",
            "hover": "group-hover:bg-neutral-300 group-hover:text-primary-200",
            "pressed": "group-active:bg-neutral-300/40 group-active:text-primary-200",
            "loading": "group-aria-busy:bg-neutral-300/40 group-aria-busy:text-primary-200",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "ghost": {
            "base": "bg-transparent text-primary-300 group-aria-busy:opacity-0",
            "hover": "group-hover:bg-neutral-200/40 group-hover:text-primary-200",
            "pressed": "group-active:bg-neutral-300 group-active:text-primary-200",
            "loading": "group-aria-busy:bg-neutral-300 group-aria-busy:text-primary-200",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "destructive": {
            "base": "bg-error-100 text-black group-aria-busy:opacity-0",
            "hover": "group-hover:bg-error-100/80 group-hover:text-black",
            "pressed": "group-active:bg-error-100 group-active:text-black",
            "loading": "group-aria-busy:bg-error-100 group-aria-busy:text-black",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        }
    },
    "states": {
        "fullWidth": "w-full",
        "fullWidthMobile": "w-full md:w-auto"
    },
    "slots": {
        "leadingIcon": "shrink-0",
        "trailingIcon": "shrink-0",
        "label": "truncate"
    },
    "animation": {
        "loading": "animate-spin"
    }
} as const

export type ButtonUiOptimized = typeof button

export default button