// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex",
    "type": {
        "standard": {
            "base": "flex-row items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "min-w-16 h-8 gap-1 rounded-2 px-2 py-1",
                    "icon": "!w-6 !h-6",
                    "label": "text-button-sm truncate"
                },
                "md": {
                    "container": "min-w-24 h-10 gap-1 rounded-3 px-2 py-2",
                    "icon": "!w-6 !h-6",
                    "label": "text-button-md truncate"
                },
                "lg": {
                    "container": "min-w-24 h-12 gap-2 rounded-4 px-3.5 py-3",
                    "icon": "!w-6 !h-6",
                    "label": "text-button-lg truncate"
                }
            }
        },
        "icon": {
            "base": "aspect-square p-0 flex items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "h-8 rounded-2",
                    "icon": "w-4"
                },
                "md": {
                    "container": "h-10 rounded-3",
                    "icon": "w-6"
                },
                "lg": {
                    "container": "h-12 rounded-4",
                    "icon": "w-6"
                }
            }
        },
        "caption": {
            "base": "flex-col text-center justify-center items-center",
            "sizes": {
                "sm": {
                    "container": "h-12 gap-0.5 rounded-2 px-4 py-1",
                    "label": "text-button-sm truncate",
                    "caption": "text-button-caption truncate"
                },
                "md": {
                    "container": "h-14 gap-1 rounded-4 px-6 py-1",
                    "label": "text-button-md truncate",
                    "caption": "text-button-caption truncate"
                },
                "lg": {
                    "container": "h-16 gap-1 rounded-4 px-6 py-1",
                    "label": "text-button-lg truncate",
                    "caption": "text-button-caption truncate"
                }
            }
        },
        "slab": {
            "base": "flex-col items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "min-w-18 max-w-38 h-14 gap-1 rounded-2 px-4 py-1",
                    "icon": "w-6",
                    "label": "text-button-caption truncate"
                }
            }
        },
        "action": {
            "base": "flex-col items-center justify-center text-center text-white gap-1.5",
            "sizes": {
                "sm": {
                    "container": "flex justify-center items-center w-12 h-12 rounded-2",
                    "icon": "w-6",
                    "label": "text-button-caption truncate"
                }
            }
        }
    },
    "variant": {
        "filled": {
            "base": "[border-width:0rem] border-transparent bg-primary-300 text-neutral-500",
            "hover": "group-hover:bg-primary-200 group-hover:text-neutral-500",
            "pressed": "group-active:bg-primary-100 group-active:text-neutral-500",
            "loading": "group-aria-busy:bg-primary-100 group-aria-busy:text-neutral-500",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        },
        "outline": {
            "base": "border-2 border-primary-300 bg-primary-300/10 text-white",
            "hover": "group-hover:border-primary-200 group-hover:bg-primary-200/10 group-hover:text-white",
            "pressed": "group-active:border-primary-100 group-active:bg-primary-100/10 group-active:text-white",
            "loading": "group-aria-busy:border-primary-100 group-aria-busy:bg-primary-100/10 group-aria-busy:text-white",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "soft-primary": {
            "base": "[border-width:0rem] border-transparent bg-neutral-400 text-primary-300",
            "hover": "group-hover:bg-neutral-300 group-hover:text-primary-200",
            "pressed": "group-active:bg-neutral-400/80 group-active:text-primary-200",
            "loading": "group-aria-busy:bg-neutral-400/80 group-aria-busy:text-primary-200",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "soft-neutral": {
            "base": "[border-width:0rem] border-transparent bg-neutral-400 text-white",
            "hover": "group-hover:bg-neutral-300 group-hover:text-white",
            "pressed": "group-active:bg-neutral-400/80 group-active:text-white",
            "loading": "group-aria-busy:bg-neutral-400/80 group-aria-busy:text-white",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "ghost": {
            "base": "[border-width:0rem] border-transparent bg-transparent text-white",
            "hover": "group-hover:bg-neutral-300/80 group-hover:text-white",
            "pressed": "group-active:bg-neutral-400/80 group-active:text-white",
            "loading": "group-aria-busy:bg-neutral-400/80 group-aria-busy:text-white",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "destructive": {
            "base": "[border-width:0rem] border-transparent bg-error-100 text-black",
            "hover": "group-hover:bg-error-100/80 group-hover:text-black",
            "pressed": "group-active:bg-error-100 group-active:text-black",
            "loading": "group-aria-busy:bg-error-100 group-aria-busy:text-black",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        }
    },
    "states": {
        "fullWidth": "w-full"
    },
    "slots": {
        "leadingIcon": "shrink-0",
        "trailingIcon": "shrink-0",
        "label": "truncate"
    }
} as const

export type ButtonUiOptimized = typeof button

export default button