// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-inline-action-notification p-4 bg-white rounded-16 text-neutral-800",
    "slots": {
        "container": "flex gap-2 lg:gap-4",
        "icon": "h-8 w-8",
        "content": "flex flex-col justify-between w-full gap-3 lg:gap-4 lg:flex-row",
        "message": "",
        "title": "h3 font-bold",
        "actions": "grid grid-flow-col gap-x-2 lg:gap-x-4"
    }
} as const

export default button