// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type {Config} from "tailwindcss";
import plugin from "tailwindcss/plugin";

const button: Partial<Config> = {
    plugins: [
        plugin(({ addComponents }) => {
            addComponents({
                '.ui-button': {
                    '&.primary': {
                        '.ui-button--primary': {
                            backgroundColor: "rgb(var(--color-primary-300) / 1)",
                            color: "rgb(var(--color-white))",
                        },

                        '&:not(:disabled):hover .ui-button--primary': {
                            backgroundColor: "rgb(var(--color-primary-200) / 1)",
                            color: "rgb(var(--color-primary-50) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--primary, &[aria-busy="true"] .ui-button--primary': {
                            backgroundColor: "rgb(var(--color-primary-400) / 1)",
                            color: "rgb(var(--color-primary-50) / 1)",
                        },
                    },

                    '&.destructive': {
                        '.ui-button--destructive': {
                            backgroundColor: "rgb(var(--color-error-100) / 1)",
                            color: "rgb(var(--color-white))",
                        },

                        '&:not(:disabled):hover .ui-button--destructive': {
                            backgroundColor: "rgb(var(--color-error-100) / 0.8)",
                            color: "rgb(var(--color-neutral-50) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--destructive, &[aria-busy="true"] .ui-button--destructive': {
                            backgroundColor: "rgb(var(--color-error-100) / 1)",
                            color: "rgb(var(--color-neutral-50) / 1)",
                        },
                    },

                    '&.secondary': {
                        '.ui-button--secondary': {
                            borderWidth: '2px',
                            borderColor: "rgb(var(--color-primary-200) / 0.4)",
                            backgroundColor: "rgb(var(--color-primary-50) / 0.4)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--secondary': {
                            borderColor: "rgb(var(--color-primary-200) / 1)",
                            backgroundColor: "rgb(var(--color-primary-50) / 0.4)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--secondary, &[aria-busy="true"] .ui-button--secondary': {
                            borderColor: "rgb(var(--color-primary-300) / 1)",
                            backgroundColor: "rgb(var(--color-primary-100) / 0.4)",
                            color: "rgb(var(--color-primary-300) / 1)",
                        },
                    },

                    '&.tertiary': {
                        '.ui-button--tertiary': {
                            backgroundColor: "rgb(var(--color-neutral-800) / 0.1)",
                            color: "rgb(var(--color-neutral-600) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--tertiary': {
                            backgroundColor: "rgb(var(--color-neutral-200) / 0.8)",
                            color: "rgb(var(--color-neutral-700) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--tertiary, &[aria-busy="true"] .ui-button--tertiary': {
                            backgroundColor: "rgb(var(--color-neutral-300) / 0.4)",
                            color: "rgb(var(--color-neutral-700) / 1)",
                        },
                    },

                    '&.ghost': {
                        '.ui-button--ghost': {
                            backgroundColor: "var(--color-transparent)",
                            color: "rgb(var(--color-neutral-600) / 1)",
                        },

                        '&:not(:disabled):hover .ui-button--ghost': {
                            backgroundColor: "rgb(var(--color-neutral-200) / 0.8)",
                            color: "rgb(var(--color-neutral-700) / 1)",
                        },

                        '&:not(:disabled):active .ui-button--ghost, &[aria-busy="true"] .ui-button--ghost': {
                            backgroundColor: "rgb(var(--color-neutral-300) / 0.4)",
                            color: "rgb(var(--color-neutral-700) / 1)",
                        },
                    },

                    '&:disabled:not([aria-busy="true"])': {
                        '&.primary, &.destructive': {
                            opacity: '0.45'
                        },
                        '&.secondary, &.tertiary, &.ghost': {
                            opacity: '0.45'
                        }
                    },
                    '&[aria-busy="true"]': {
                        '.ui-button__content': {
                            opacity: '0'
                        }
                    },

                    '&.slab': {
                        '&.tertiary-alt ': {
                            '.ui-button--tertiary': {
                                backgroundColor: "rgb(var(--color-neutral-800) / 0.1)",
                                border: "2px solid var(--color-transparent)",
                                color: "rgb(var(--color-neutral-600) / 1)",
                                '&:hover': {
                                    backgroundColor: "rgb(var(--color-neutral-200) / 0.8)",
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                                '&:active': {
                                    backgroundColor: "rgb(var(--color-neutral-300) / 0.4)",
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                                '&:hover, &:active, &:disabled': {
                                    borderColor: 'transparent',
                                }
                            }
                        }
                    },
                    '&.icon': {
                        '&.tertiary-alt': {
                            '.ui-button--tertiary': {
                                color: "rgb(var(--color-neutral-600) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                            }
                        },
                        '&.ghost-alt': {
                            '.ui-button--ghost': {
                                color: "rgb(var(--color-neutral-600) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                            }
                        }
                    },
                    '&.action': {
                        '&.tertiary-alt': {
                            '.ui-button--tertiary': {
                                color: "rgb(var(--color-neutral-600) / 1)",
                                '&:hover': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                                '&:active': {
                                    color: "rgb(var(--color-neutral-700) / 1)",
                                },
                            }
                        }
                    }
                },
            })
        }),
    ],
}

export default button
