// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex",
    "type": {
        "standard": {
            "base": "flex-row items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "min-w-16 h-8 gap-1 rounded-8 px-2 py-1",
                    "icon": "!w-4 !h-4",
                    "label": "text-button-sm truncate"
                },
                "md": {
                    "container": "min-w-24 h-10 gap-1 rounded-12 px-2 py-2",
                    "icon": "",
                    "label": "text-button-md truncate"
                },
                "lg": {
                    "container": "min-w-24 h-12 gap-2 rounded-16 px-3.5 py-3",
                    "icon": "",
                    "label": "text-button-lg truncate"
                }
            }
        },
        "icon": {
            "base": "aspect-square p-0 flex items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "h-8 rounded-8",
                    "icon": "!w-4 !h-4"
                },
                "md": {
                    "container": "h-10 rounded-12",
                    "icon": "w-6"
                },
                "lg": {
                    "container": "h-12 rounded-16",
                    "icon": "w-6"
                }
            }
        },
        "caption": {
            "base": "flex-col text-center justify-center items-center",
            "sizes": {
                "sm": {
                    "container": "h-12 gap-0.5 rounded-8 px-4 py-1",
                    "label": "text-button-sm truncate",
                    "caption": "text-button-caption truncate opacity-85"
                },
                "md": {
                    "container": "h-14 gap-1 rounded-12 px-6 py-1",
                    "label": "text-button-md truncate",
                    "caption": "text-button-caption truncate opacity-85"
                },
                "lg": {
                    "container": "h-16 gap-1 rounded-16 px-6 py-1",
                    "label": "text-button-lg truncate",
                    "caption": "text-button-caption truncate opacity-85"
                }
            }
        },
        "slab": {
            "base": "flex-col items-center justify-center",
            "sizes": {
                "sm": {
                    "container": "min-w-18 max-w-38 h-14 gap-1 rounded-12 px-4 py-1",
                    "icon": "w-6",
                    "label": "text-button-caption truncate"
                }
            }
        },
        "action": {
            "base": "flex-col items-center justify-center text-center gap-1.5",
            "sizes": {
                "sm": {
                    "container": "flex justify-center items-center w-12 h-12 rounded-12",
                    "icon": "w-6",
                    "label": "text-button-caption truncate"
                }
            }
        }
    },
    "variant": {
        "primary": {
            "base": "bg-primary-300 text-white group-aria-busy:opacity-0",
            "hover": "group-hover:bg-primary-200 group-hover:text-primary-50",
            "pressed": "group-active:bg-primary-400 group-active:text-primary-50",
            "loading": "group-aria-busy:bg-primary-400 group-aria-busy:text-primary-50",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        },
        "secondary": {
            "base": "border-2 border-primary-200/40 bg-primary-50/40 text-primary-300 group-aria-busy:opacity-0",
            "hover": "group-hover:border-primary-200 group-hover:bg-primary-50/40 group-hover:text-primary-300",
            "pressed": "group-active:border-primary-300 group-active:bg-primary-100/40 group-active:text-primary-300",
            "loading": "border-2 group-aria-busy:border-primary-300 group-aria-busy:bg-primary-100/40 group-aria-busy:text-primary-300",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "tertiary": {
            "base": "border-transparent bg-neutral-800/10 text-neutral-600 group-aria-busy:opacity-0",
            "hover": "group-hover:bg-neutral-200/80 group-hover:text-neutral-700",
            "pressed": "group-active:bg-neutral-300/40 group-active:text-neutral-700",
            "loading": "group-aria-busy:bg-neutral-300/40 group-aria-busy:text-neutral-700",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "ghost": {
            "base": "bg-transparent text-neutral-600 group-aria-busy:opacity-0",
            "hover": "group-hover:bg-neutral-800/10 group-hover:text-neutral-700",
            "pressed": "group-active:bg-neutral-200/80 group-active:text-neutral-700",
            "loading": "group-aria-busy:bg-neutral-200/80 group-aria-busy:text-neutral-700",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-45"
        },
        "destructive": {
            "base": "bg-error-100 text-white group-aria-busy:opacity-0",
            "hover": "group-hover:bg-error-100/80 group-hover:text-[248_247_250]",
            "pressed": "group-active:bg-error-100 group-active:text-[248_247_250]",
            "loading": "group-aria-busy:bg-error-100 group-aria-busy:text-[248_247_250]",
            "disabled": "[&:disabled:not([aria-busy=true])]:opacity-25"
        }
    },
    "states": {
        "fullWidth": "w-full"
    },
    "slots": {
        "leadingIcon": "shrink-0",
        "trailingIcon": "shrink-0",
        "label": "truncate"
    },
    "animation": {
        "loading": "animate-spin"
    }
} as const

export type ButtonUiOptimized = typeof button

export default button