// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex",
    "type": {
        "standard": {
            "base": "flex-row items-center justify-center",
            "sizes": {
                "sm": {
                    "base": "rounded-8",
                    "container": "h-32 gap-4 rounded-8 px-12 py-4",
                    "icon": "!w-16 !h-16",
                    "label": "text-button-sm truncate lowercase first-letter:uppercase"
                },
                "md": {
                    "base": "rounded-12",
                    "container": "h-40 gap-4 rounded-12 px-12 py-8",
                    "icon": "",
                    "label": "text-button-md truncate lowercase first-letter:uppercase"
                },
                "lg": {
                    "base": "rounded-12",
                    "container": "h-[3rem] gap-8 rounded-12 px-16 py-12",
                    "icon": "",
                    "label": "text-button-lg truncate lowercase first-letter:uppercase"
                }
            }
        },
        "icon": {
            "base": "aspect-square p-0 flex items-center justify-center",
            "sizes": {
                "sm": {
                    "base": "rounded-12",
                    "container": "h-32 rounded-12",
                    "icon": "!w-16 !h-16"
                },
                "md": {
                    "base": "rounded-12",
                    "container": "h-40 rounded-12",
                    "icon": "w-24"
                },
                "lg": {
                    "base": "rounded-12",
                    "container": "h-[3rem] rounded-12",
                    "icon": "w-24"
                }
            }
        },
        "caption": {
            "base": "flex-col text-center justify-center items-center",
            "sizes": {
                "sm": {
                    "base": "rounded-8",
                    "container": "h-[3rem] gap-2 rounded-8 px-16 py-4",
                    "label": "text-button-sm truncate lowercase first-letter:uppercase",
                    "caption": "text-button-caption truncate lowercase first-letter:uppercase opacity-85"
                },
                "md": {
                    "base": "rounded-12",
                    "container": "h-[3.5rem] gap-4 rounded-12 px-24 py-4",
                    "label": "text-button-md truncate lowercase first-letter:uppercase",
                    "caption": "text-button-caption truncate lowercase first-letter:uppercase opacity-85"
                },
                "lg": {
                    "base": "rounded-12",
                    "container": "h-[4rem] gap-4 rounded-12 px-24 py-4",
                    "label": "text-button-lg truncate lowercase first-letter:uppercase",
                    "caption": "text-button-caption truncate lowercase first-letter:uppercase opacity-85"
                }
            }
        },
        "slab": {
            "base": "flex-col items-center justify-center",
            "sizes": {
                "sm": {
                    "base": "rounded-12",
                    "container": "h-[3.75rem] gap-4 rounded-12 px-16 py-4",
                    "icon": "w-6",
                    "label": "text-button-xs truncate lowercase first-letter:uppercase"
                }
            }
        },
        "action": {
            "base": "flex-col items-center justify-center text-center gap-[0.375rem] gap-[0.375rem]",
            "sizes": {
                "sm": {
                    "container": "flex justify-center items-center w-[3rem] h-[3rem] rounded-full",
                    "icon": "w-6",
                    "label": "text-button-caption text-neutral-800 truncate lowercase first-letter:uppercase"
                }
            }
        }
    },
    "variant": {
        "tertiaryAltSlabDefaultBorder": {
            "base": "border-2 border-transparent"
        }
    },
    "states": {
        "fullWidth": "w-full",
        "fullWidthMobile": "w-full md:w-auto"
    },
    "slots": {
        "leadingIcon": "shrink-0",
        "trailingIcon": "shrink-0",
        "label": "truncate lowercase first-letter:uppercase"
    },
    "animation": {
        "loading": "animate-spin"
    }
} as const

export type ButtonUiOptimized = typeof button

export default button