// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-base-notification rounded-16",
    "variant": {
        "neutral": "bg-white text-neutral-800",
        "success": "bg-secondary-300 text-neutral-800",
        "error": "bg-error-100 text-white"
    }
} as const

export default button