// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "relative flex items-center justify-center",
    "slots": {
        "svg": "relative z-10 h-full w-full",
        "trail": "stroke-neutral-800/10",
        "line": "stroke-primary-300",
        "content": "absolute inset-0 flex items-center justify-center rounded-full bg-transparent"
    }
} as const

export default button