// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-faq-item flex flex-col overflow-hidden rounded-16 border-neutral-200/40 bg-transparent text-fg-primary border px-4 py-2",
    "slots": {
        "iconOpened": "rotate-180"
    }
} as const

export default button