// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "inline-flex items-center justify-center overflow-hidden shrink-0 upper-case",
    "size": {
        "default": {
            "container": "h-4 rounded-full px-2",
            "label": "text-caption font-bold uppercase whitespace-nowrap"
        }
    },
    "variant": {
        "status-error": "bg-error-100/80 text-neutral-800",
        "status-warning": "bg-warning-100/80 text-neutral-800",
        "status-success": "bg-success-100/80 text-neutral-800",
        "navigation-default": "bg-primary-300 text-white",
        "navigation-new": "bg-error-100 text-white",
        "neutral-default": "bg-neutral-100 text-neutral-800",
        "neutral-error": "bg-neutral-100 text-error-100"
    },
    "slots": {
        "label": "text-caption font-bold uppercase whitespace-nowrap"
    }
} as const

export default button