// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-accordion flex flex-col overflow-hidden rounded-12 border-neutral-800/10 bg-white text-fg-primary border px-4 py-2",
    "slots": {
        "iconOpened": "rotate-180"
    }
} as const

export default button