// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-read-more",
    "slots": {
        "contentWrapper": "relative overflow-hidden transition-height mb-2",
        "collapsedOverlay": "after:pointer-events-none after:absolute after:bottom-0 after:left-0 after:block after:h-full after:w-full after:content-empty",
        "toggle": "mt-2"
    }
} as const

export default button