// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const basicControls: Partial<Config> = {
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.ui-input': {
          '@apply relative flex flex-col': {},
          gap: "var(--spacing-4)",

          '&[data-disabled="true"]': {
            opacity: "0.45",
          },

          '&:focus-within .ui-input__label': {
            color: "rgb(var(--color-primary-300) / 1)",
          },

          '&[data-invalid="true"] .ui-input__message': {
            color: "rgb(var(--color-error-100) / 1)",
          },

          '&:focus-within .ui-input__message, &:focus-within .ui-input__error-message': {
            color: "rgb(var(--color-neutral-100) / 1)",
          },
        },

        '.ui-input__field': {
          '@apply flex items-center w-full overflow-hidden border-solid py-8 px-12': {},
          height: "3.5rem",
          gap: "var(--spacing-8)",
          backgroundColor: "rgb(var(--color-neutral-200) / 0.4)",
          borderColor: "var(--color-transparent)",
          borderStyle: 'solid',
          borderWidth: "var(--radius-2)",
          borderRadius: "var(--radius-16)",

          '&:not(:focus-within):not([data-invalid="true"]):not([data-disabled="true"]):hover': {
            borderColor: "rgb(var(--color-primary-50) / 1)",
          },

          '&:focus-within': {
            borderColor: "rgb(var(--color-primary-300) / 1)",
          },

          '&[data-invalid="true"]:not(:focus-within)': {
            borderColor: "rgb(var(--color-error-100) / 1)",
          },
        },

        '.ui-input__label': {
          '@apply left-0 origin-left transition-all duration-150 ease-out w-full text-body': {},
          color: "rgb(var(--color-neutral-100) / 1)",
        },

        '.ui-input__message': {
          '@apply flex gap-4 text-caption': {},
          paddingInline: "var(--spacing-16)",
          color: "rgb(var(--color-neutral-100) / 1)",

          '&--error': {
            color: "rgb(var(--color-error-100) / 1)",
          },
          '&--success': {
            color: "rgb(var(--color-success-100) / 1)",
          }
        },
      })
    }),
  ],
}

export default basicControls
