// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const select: Partial<Config> = {
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.ui-select': {
          '@apply relative flex flex-col': {},
          gap: "var(--spacing-4)",

          '&--sm .ui-select__field': {
            height: "2.75rem",
            padding: "var(--spacing-8)",
            borderRadius: "var(--radius-8)",
          },

          '&--sm .ui-select__content': {
            '@apply h-24': {},
          },

          '&--default .ui-select__field': {
            height: "3.5rem",
            padding: "var(--radius-8) var(--radius-12)",
            borderRadius: "var(--radius-16)",
          },

          '&--default .ui-select__content': {
            '@apply h-[2.25rem]': {},
          },

          '&--floating-label .ui-select__label': {
            '@apply top-0 translate-y-0 scale-100 text-caption': {},
          },

          '&--floating-label .ui-select__displayed-value': {
            '@apply top-auto bottom-0 translate-y-0 scale-100': {},
          },

          '&--disabled': {
            opacity: "0.45",
          },

          '&:not([data-open="true"]):not([data-invalid="true"]):not([data-disabled="true"]):hover .ui-select__field': {
            borderColor: "rgb(var(--color-primary-50) / 1)",
          },

          '&--open': {
            '.ui-select__field': {
              borderColor: "rgb(var(--color-primary-300) / 1)",
            },

            '.ui-select__label': {
              color: "rgb(var(--color-primary-300) / 1)",
            },

            '.ui-select__dropdown-icon': {
              transform: 'rotate(180deg)',
            },
          },

          '&--error .ui-select__field': {
            borderColor: "rgb(var(--color-error-100) / 1)",
          },

          '&[data-invalid="true"] .ui-input__message': {
            color: "rgb(var(--color-error-100) / 1)",
          },

          '&__field': {
            '@apply flex items-center w-full overflow-hidden border-solid text-left cursor-pointer focus-visible:outline-none disabled:cursor-not-allowed': {},
            gap: "var(--spacing-8)",
            backgroundColor: "rgb(var(--color-neutral-200) / 0.4)",
            borderColor: "var(--color-transparent)",
            borderWidth: "var(--radius-2)",
          },

          '&__content': {
            '@apply relative flex min-w-0 flex-1 flex-col justify-center overflow-hidden': {},
          },

          '&__label': {
            '@apply absolute top-1/2 -translate-y-1/2 left-0 origin-left transition-all duration-150 ease-out w-full text-body min-w-0 truncate': {},
            color: "rgb(var(--color-neutral-100) / 1)",
          },

          '&__displayed-value': {
            '@apply absolute z-1 w-full min-w-0 text-body truncate text-left': {},

            '&--value': {
              '@apply font-medium': {},
              color: "rgb(var(--color-white))",
            },

            '&--placeholder': {
              color: "rgb(var(--color-neutral-100) / 1)",
            },
          },

          '&__icon': {
            '@apply shrink-0 size-6': {},
            color: "rgb(var(--color-neutral-100) / 1)",

            '&--selected': {
              color: "var(--fg-status-success)",
            },
          },

          '&__dropdown-icon': {
            '@apply transition-transform': {},
          },

          '&__action': {
            '@apply ml-auto shrink-0': {},
          },

          '&__list': {
            '@apply z-20 overflow-hidden': {},
            backgroundColor: "rgb(var(--color-neutral-300) / 1)",
            borderRadius: "var(--radius-16)",
            boxShadow: "0px 0px 16px 0px var(--effect-shadow-default), 0px 0px 4px 2px var(--effect-shadow-default)",
          },
        },
      })
    }),
  ],
}

export default select
