// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const select: Partial<Config> = {
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.ui-select': {
          '&__icon': {
            flexShrink: '0',
            width: '1.5rem',
            height: '1.5rem',
            color: "rgb(var(--color-neutral-100) / 1)",
            '&--selected': {
              color: "var(--fg-status-success)"
            }
          },
          '&__text': {
            minWidth: '0',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          },
          '.ui-select__displayed-value': {
            textAlign: 'left',
          },
          '&--disabled': {
            opacity: "0.45",
          },
          '.ui-select__list': {
            boxShadow: "0px 0px 16px 0px var(--effect-shadow-default), 0px 0px 4px 2px var(--effect-shadow-default)",
          },
          '&--open': {
            '.ui-select__field': {
              borderColor: "rgb(var(--color-primary-300) / 1)",
            },
            '.ui-select__label': {
              color: "rgb(var(--color-primary-300) / 1)",
            },
            '.ui-select__dropdown-icon': {
              transform: 'rotate(180deg)',
            },
          },
        },
      })
    }),
  ],
}

export default select
