// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const smcNotification: Partial<Config> = {
  plugins: [
    plugin(({ addBase, addComponents }) => {
      addBase({
        '@keyframes smc-notification-progress': {
          to: { transform: 'translateX(0)' },
        },
        '.smc-notification-enter-active': {
          transition: 'transform 500ms cubic-bezier(0.5, 0, 0, 1), opacity 500ms cubic-bezier(0.5, 0, 0, 1)',
        },
        '.smc-notification-leave-active': {
          transition: 'transform 500ms ease-out, opacity 500ms ease-out',
        },
        '.smc-notification-enter-from': {
          transform: 'translateY(-100vh)',
          opacity: '0',
        },
        '.smc-notification-leave-to': {
          transform: 'translateY(calc(-100% - 1rem))',
          opacity: '0',
        },
      })

      addComponents({
        '.smc-notification': {
          width: '100%',
          background: "linear-gradient(to top, rgb(var(--color-primary-300) / 0) 0%, rgb(var(--color-primary-300) / 0.1) 2rem, rgb(var(--color-primary-300) / 0.4) 5rem, rgb(var(--color-primary-300)) 100%)",
          '@screen md': {
            width: '28rem',
            background: 'none',
          },
          '&__card': {
            background: "var(--bg-page-surface)",
            color: "var(--fg-page-secondary)",
            boxShadow: "0 8px 16px -8px rgb(var(--color-primary-200) / 40%)",
          },
          '&__title': { color: "var(--fg-page-brand)" },
          '&__title :is(b, strong)': { color: 'inherit', fontWeight: 'inherit' },
          '&__message :is(b, strong)': {
            color: "var(--fg-page-primary)",
            fontWeight: "var(--text-fontweight-bold)",
          },
          '&__copy a': {
            color: "var(--fg-page-link-default)",
            textDecoration: 'underline',
          },
          '&__image': {
            width: 'clamp(4rem, 20%, 5rem)',
            aspectRatio: '1',
            '@screen md': { width: 'clamp(4rem, 20%, 6rem)' },
          },
          '&__actions > *': {
            flex: '1',
            minWidth: '0',
            '@screen md': { flex: 'none' },
          },
          '&__dismiss': {
            background: "var(--bg-page-surface)",
            color: "var(--fg-page-secondary)",
            borderColor: "var(--bg-page-surface)",
            boxShadow: "var(--shadow-fg-default)",
            '&--active': { color: "var(--fg-page-brand)" },
          },
          '&__progress': {
            background: "rgb(var(--color-primary-50))",
            top: '0',
            bottom: '0',
            left: '0',
            width: '100%',
            borderRadius: '0 24px 24px 0',
            transform: 'translateX(-100%)',
            '&--running': { animation: 'smc-notification-progress linear forwards' },
            '&--active': {
              transform: 'translateX(0)',
            },
          },
        },
      })
    }),
  ],
}

export default smcNotification
