// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-input group flex flex-col relative gap-1 data-[disabled=true]:opacity-45",
    "size": {
        "default": {
            "field": "rounded-12 h-14 px-3.5 py-2.5"
        }
    },
    "slots": {
        "field": "flex items-center w-full overflow-hidden border-solid border-2 gap-2 bg-neutral-200/40 hover:[&:not(:focus-within)]:border-primary-50 focus-within:border-primary-300 data-[invalid=true]:border-error-100",
        "content": "relative flex min-w-0 flex-1 flex-col justify-center h-[2.25rem]",
        "label": "text-body font-medium duration-150 text-neutral-100 group-focus-within:text-primary-300 group-data-[invalid=true]:text-error-100 min-w-0 truncate",
        "value": "text-body font-medium placeholder:font-normal text-white placeholder:text-neutral-100 min-w-0 truncate",
        "message": "px-4 text-neutral-100 group-data-[invalid=true]:!text-error-100 text-caption",
        "leadingIcon": "shrink-0 size-6 text-neutral-100",
        "trailingIcon": "shrink-0 size-6 text-neutral-100",
        "action": "shrink-0"
    }
} as const

export default button