// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-link text-link",
    "size": {
        "default": "text-body",
        "body-sm": "text-body-sm",
        "caption": "text-caption"
    }
} as const

export default button