// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "w-full h-full fixed top-0 left-0 top-0 bottom-0 bg-neutral-50 z-index-100 bg-[var(--bg-overlay)]",
    "slots": {
        "modalContainer": "flex items-center justify-center max-h-80dvh min-w-[20rem] max-w-100dvw md:w-full cursor-default p-16 rounded-t-24 md:rounded-24 bg-bg-surface",
        "modalContent": "max-w-full w-full box-border flex flex-col gap-6 overflow-hidden pb-safe gap-24",
        "modalHeader": "flex justify-space-between items-center w-full text-subtitle gap-8 text-fg-primary",
        "modalHeaderIcons": "w-6 h-6",
        "modalHeaderTitle": "shrink grow basis-auto text-center",
        "modalBottomActions": "flex w-full justify-center items-center gap-16"
    },
    "sizes": {
        "s": "md:w-[calc(100dvw-2rem)] md:max-w-[27rem]",
        "m": "md:w-[calc(100dvw-2rem)] md:max-w-[40rem]",
        "l": "md:w-[calc(100dvw-2rem)] md:max-w-[52.5rem]",
        "xl": "md:w-[calc(100dvw-2rem)] md:max-w-[67.5rem]",
        "fullScreen": "h-full max-w-full !rounded-0 !justify-start"
    },
    "transitionGroup": {
        "desktop": {
            "enterActiveClass": "transition-all duration-500",
            "enterFromClass": "opacity-0",
            "leaveActiveClass": "transition-all duration-500",
            "leaveToClass": "opacity-0"
        },
        "mobile": {
            "enterActiveClass": "transition-all duration-500",
            "enterFromClass": "opacity-0 translate-y-[450px]",
            "leaveActiveClass": "transition-all duration-500",
            "leaveToClass": "opacity-0 translate-y-[450px]"
        }
    }
} as const

export default button