// Auto-generated by scripts/replace-component-colors.ts
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "ui-accordion flex flex-col overflow-hidden border transition-colors rounded-16 text-fg-primary px-16 py-12",
    "slots": {
        "iconOpened": "rotate-180"
    },
    "states": {
        "opened": "bg-primary-50/10 border-primary-50/10",
        "default": "border-neutral-50/10 bg-neutral-300"
    }
} as const

export default button