// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "p-2",
    "type": {
        "base": "flex items-center justify-center w-full text-center",
        "icon": "flex items-center gap-2 justify-start w-full"
    }
} as const

export default button