// Auto-generated by scripts/replace-component-presets.ts
// Do not edit manually. Update preset.ts or CSS token mappings and rerun the generator.

import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const input: Partial<Config> = {
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.ui-input-control': {
          '&.ui-input--floating-label .ui-input__label': {
            '@apply top-0 translate-y-0 scale-100 text-caption': {},
          },

          '&.ui-input--floating-label .ui-input__value': {
            '@apply top-auto bottom-0 translate-y-0 scale-100': {},
          },

          '.ui-input__content': {
            '@apply relative flex min-w-0 flex-1 flex-col justify-center h-[2.25rem]': {},
          },

          '.ui-input__label': {
            '@apply absolute top-1/2 -translate-y-1/2 min-w-0 truncate': {},
          },

          '.ui-input__icon': {
            '@apply shrink-0 size-24': {},
            color: "rgb(var(--color-neutral-400) / 1)",
          },

          '.ui-input__action': {
            '@apply shrink-0': {},
          },

          '.ui-input__value': {
            '@apply text-body font-medium absolute z-1 w-full min-w-0 border-0 bg-transparent p-0 outline-none truncate': {},
            color: "rgb(var(--color-neutral-600) / 1)",

            '&:disabled': {
              '@apply cursor-not-allowed': {},
            },

            '&::placeholder': {
              '@apply font-normal opacity-100': {},
              color: "rgb(var(--color-neutral-300) / 1)",
            },
          },
        },
      })
    }),
  ],
}

export default input
