// Auto-generated by scripts/replace-component-colors.mjs
// Do not edit manually. Update theme.ts or CSS token mappings and rerun the generator.

const button = {
    "base": "flex items-center gap-1 overflow-x-auto min-h-px min-w-px",
    "item": {
        "base": "flex shrink-0 items-center justify-center h-10 gap-2 px-4 py-2 transition-colors rounded-8",
        "default": "text-neutral-500",
        "hover": "hover:bg-neutral-400/10 hover:text-neutral-500",
        "selected": "bg-neutral-700/10 text-neutral-800",
        "disabled": "pointer-events-none opacity-45"
    },
    "slots": {
        "label": "text-body-sm font-bold uppercase whitespace-nowrap text-center",
        "accent": "size-2 shrink-0 rounded-full bg-fg-status-error"
    }
} as const

export default button